name: Trigger auto deployment for zlhe-test-user-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/zlhe-test-user-service-AutoDeployTrigger-600886af-50cb-41e7-be38-5c3fa5c82e2f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ZLHETESTUSERSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ZLHETESTUSERSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ZLHETESTUSERSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.ZLHETESTUSERSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ZLHETESTUSERSERVICE_REGISTRY_PASSWORD }}
          containerAppName: zlhe-test-user-service
          resourceGroup: zlhe-test
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


